### ISSUE TITLE
Node Version, OSX support

### ISSUE THREAD

**Issue by zewa666** [martonsagi/aurelia-cli-pacman#3]
I've tried aurelia-cli-pacman under OSX and it works properly 👍 

What I found though is that certain parts of the tool use modern ES6 constructs, which I think will need a version of Node 5.0.0 at least. Guess stating that as a dependency might be useful

**Comment by martonsagi** [comment]
Thanks again! So, this cross-platform thingy actually works. :-)

I have a pretty old Node v4.4.4 on Windows 10 (I know, it should be updated..) and it works without issues. That's why I took the liberty to use such new language features. 

Supporting the current LTS version would be better than a simple statement. Perhaps, I missed something? All suggestions are welcome. Thanks

**Comment by zewa666** [comment]
@martonsagi regarding Node, oh I'm totally sorry about that. Forgot that you actually just hook into an existing CLI setup. Aurelia-CLI uses a `.babelrc` file together with some devdependencies, which ensures that the execution can happen on a ESNext basis. The [CLI docs](http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/the-aurelia-cli/1) therefore also state that  the minimum is Node 4.x. So we're good here no need for a change.

**Comment by martonsagi** [comment]
Thanks for clarification. I've updated README to be aligned with CLI docs.
